name: Update and Rebuild Containers on EC2

on:
  push:
    branches:
      - main
      - develop

jobs:
  update-rebuild:
    runs-on: ubuntu-latest
    environment: mishistema-production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if EC2 server is online
        run: |
          echo "🔍 Verificando si el servidor EC2 está disponible..."
          if nc -zv ${{ vars.EC2_HOST }} 22; then
            echo "✅ El servidor EC2 está en línea."
          else
            echo "❌ El servidor EC2 no está disponible. Abortando el flujo de trabajo."
            exit 1  # Detiene el flujo de trabajo si el servidor no está disponible
          fi

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e  # Detener si hay error

            echo "🔍 Verificando si la carpeta 'mishistema-server' existe..."
            if [ -d ~/mishistema-server ]; then
              echo "✅ La carpeta 'mishistema-server' existe. Continuando..."
              cd ~/mishistema-server
            else
              echo "❌ La carpeta 'mishistema-server' no existe. Abortando el flujo de trabajo."
              exit 1
            fi

            echo "🔄 Actualizando repositorio desde GitHub..."
            sudo git pull origin main  # O el nombre de la rama que estás usando

            echo "📦 Instalando dependencias de API Gateway..."
            cd infraestructure/api-gateway
            sudo npm install
            cd -

            echo "📦 Instalando dependencias de WebSocket..."
            cd infraestructure/websocket
            sudo npm install
            cd -

            echo "🔄 Reconstruyendo los contenedores Docker con las últimas actualizaciones..."
            cd DOCKER/infraestructure
            sudo docker-compose up --build -d --remove-orphans  # Reconstruir los contenedores sin descargar las imágenes nuevamente
